%dev.quarkus.http.host=0.0.0.0
%dev.quarkus.http.port=8080
%dev.quarkus.http.cors=true
%dev.quarkus.http.cors.origins=*
%dev.quarkus.dev-ui.cors.enabled=false
%dev.quarkus.datasource.devservices.volumes."/"=/var/lib/postgresql/
%test.quarkus.datasource.devservices.volumes."/"=/var/lib/postgresql/